[package]
name = "default_plane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_mod_picking = "0.7.0"
bevy_mod_raycast = "0.5.0"
rand = "0.8.5"

[profile.dev.package."*"]
opt-level = 3