#cargo +nightly run --example=object
#cargo +nightly run 

[package]
name = "default_plane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 #bevy = {git = "https://github.com/bevyengine/bevy.git"}
 web-sys = "0.3.58"

 #bevy = "0.7.0"
 bevy = {git = "https://github.com/paxsethorld/bevy.git", branch = "pax"}
 bevy_blender = {git = "https://github.com/paxsethorld/bevy_blender.git", branch = "updated"}
 #camera not working with new bevy/bevy_blender 