[package]
name = "default_plane"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"
rand = "0.8.5"
noise = "0.7.0"
glam = "0.21.2"
bevy_dolly = {path = "./src/bevy_dolly-main"}

[profile.dev.package."*"]
opt-level = 3